### ISSUE TITLE
express dependency missing from package.json

### ISSUE THREAD

**Issue by Marak** [ukd1/node-twilio#6]
You have no `express` dep in your package.json file. 

You also don't specify which version of express you require. I tried to install the latest express and run your demos, but all I get is:

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object #<Object> has no method 'bodyDecoder'
    at new AutoUri (/Users/maraksquires/dev/hook.io-twilio/node_modules/twilio/lib/auto-uri.js:32:17)
    at new Client (/Users/maraksquires/dev/hook.io-twilio/node_modules/twilio/lib/twilio.js:18:15)
    at Object.<anonymous> (/Users/maraksquires/dev/hook.io-twilio/test.js:3:15)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at Array.<anonymous> (module.js:423:10)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by ukd1** [comment]
This library is deprecated in favor of the official library - https://github.com/twilio/twilio-node
